# Generated by Django 4.2.6 on 2023-11-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_class', models.CharField(max_length=10)),
                ('classteacher', models.CharField(max_length=50)),
                ('std_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=4)),
                ('parents_name', models.CharField(max_length=50)),
                ('parents_residence', models.CharField(max_length=50)),
                ('parents_contact', models.CharField(max_length=10)),
                ('teachers_name', models.CharField(max_length=50)),
                ('teachers_classes', models.CharField(max_length=10)),
                ('teachers_subjects', models.CharField(max_length=50)),
                ('teachers_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=4)),
                ('year_of_entry', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('next_of_kin_name', models.CharField(max_length=50)),
                ('next_of_kin_residence', models.CharField(max_length=50)),
                ('next_of_kin_contact', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_fees', models.CharField(max_length=30)),
                ('cleared_fees', models.CharField(max_length=45)),
                ('fees_balance', models.CharField(max_length=45)),
                ('requirements', models.CharField(max_length=50)),
                ('student_data', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='studentpanel.student_data')),
            ],
        ),
    ]
